- README.rst
@noplay I have added a note to checkout "asyncio" branch. Kindly review it.
> Modified README

- gns3server/modules/dynamips/dynamips_hypervisor.py
In order to fix the bug #103 
I propose to add a lock like this ( i just add the with (yield from  the diff is not very readable).
This require a carefull testing.
> Lock the dynamips reader an writer

- gns3server/modules/virtualbox/virtualbox_vm.py
If you have 4 network adapter and attach only ethernet 1 and 4.
You will see eth0, eth1, eth2 and eth3 with eth0 and eth3 attached.
https://github.com/GNS3/gns3-gui/issues/255
> Fix missing adapters in VBox Virtual Machines

- README.rst
- gns3server/main.py
- gns3server/run.py
- init/gns3.conf.upstart
For avoiding trouble we need to have a very minimal main wit almost no import (example if you import logger before you can have trouble with file descriptors after the fork). That's why I have splitted it in two files.
> Proper daemon support

- gns3server/handlers/api/project_handler.py
- gns3server/modules/project.py
- gns3server/schemas/project.py
- tests/conftest.py
- tests/handlers/api/test_project.py
- tests/modules/test_project.py
This add two API call:
* list of files in a project (with temporary file like .ghost)
* download a file of a project via the API 
This allow us to implement a backup the remote server feature.
> API for list & download files of a project

- gns3server/modules/vmware/__init__.py
- gns3server/modules/vmware/vmware_vm.py
- tests/modules/vmware/test_vmware_manager.py
Fix #237
I lower all the key in VMX file. But I fear to broke something
> Make VMX reading case insensitive

- gns3server/handlers/upload_handler.py
- gns3server/templates/index.html
- gns3server/templates/layout.html
- gns3server/templates/upload.html
- tests/handlers/api/base.py
- tests/handlers/test_upload.py
> Backup upload images projects

- gns3server/modules/base_vm.py
- gns3server/modules/port_manager.py
- tests/modules/test_port_manager.py
Another version of #370
This time we replace a free TCP port if port is used and raise
a warning to the user.
> Replace by another TCP port if port is already used

- gns3server/handlers/api/qemu_handler.py
- gns3server/modules/qemu/__init__.py
- gns3server/schemas/qemu.py
- tests/handlers/api/test_qemu.py
- tests/modules/qemu/test_qemu_manager.py
- tests/utils.py
> Add  qemu capabilities

- gns3server/handlers/api/project_handler.py
- tests/handlers/api/test_project.py
> Send machine stats via the notification stream

- scripts/remote-install.sh
Code cleanup and add options for IOU
```
curl https://raw.githubusercontent.com/GNS3/gns3-server/remote_improved/scripts/remote-install.sh > gns3-remote-install.sh
bash gns3-remote-install.sh --with-openvpn --with-iou
> Add IOU support and install config in /etc

- gns3server/handlers/api/project_handler.py
- gns3server/modules/project.py
- tests/modules/test_project.py
The client will send a flag to say if the import should be done on the VM or not. Could be smarter in the futur.
> Flatten the project at export and support import for Linux

- gns3server/compute/iou/__init__.py
- gns3server/compute/iou/iou_vm.py
- gns3server/utils/file_watcher.py
- tests/utils/test_file_watcher.py
With the save as you go we need to save the startup config when a change appear instead of the old commit system.
If it's ok I will do the same for dynamips.
> Monitor IOU nvram for change

- gns3server/compute/builtin/builtin_node_factory.py
- gns3server/compute/builtin/nodes/nat.py
- gns3server/handlers/api/compute/__init__.py
- gns3server/handlers/api/compute/nat_handler.py
- gns3server/schemas/cloud.py
- gns3server/schemas/nat.py
- gns3server/schemas/node.py
- gns3server/schemas/port.py
- tests/compute/builtin/nodes/test_nat.py
- tests/conftest.py
- tests/handlers/api/compute/test_cloud.py
- tests/handlers/api/compute/test_nat.py
Not really tested but should work when we will have the GNS3 VM
> Nat node for only the GNS3 VM

- gns3server/config.py
- gns3server/controller/__init__.py
- gns3server/run.py
See https://github.com/GNS3/gns3-gui/issues/1438
> Support for profil settings

- gns3server/compute/qemu/qemu_vm.py
- tests/compute/qemu/test_qemu_vm.py
This PR set the system UUID for Qemu. I don't think it's create an issue but I open it as a PR to be sure.
Fix #711
> Set Qemu uuid for csr1000v

- gns3server/compute/base_node.py
Starting to fix little grammatical errors as I find them.  I hope that's okay!
> Fix grammar

- gns3server/compute/qemu/qemu_vm.py
- gns3server/schemas/qemu.py
- tests/compute/qemu/test_qemu_vm.py
> Allow up to 275 adapters for qemu

- gns3server/web/logger.py
> Filter /settings from log

- gns3server/controller/ports/port.py
- gns3server/controller/ports/port_factory.py
- tests/controller/test_node_port_name.py
> Fix wic numbering

- gns3server/compute/docker/__init__.py
- gns3server/compute/docker/docker_vm.py
- gns3server/controller/compute.py
- gns3server/controller/gns3vm/virtualbox_gns3_vm.py
- gns3server/controller/node.py
- gns3server/crash_report.py
- gns3server/handlers/api/compute/notification_handler.py
- gns3server/handlers/api/compute/project_handler.py
- gns3server/handlers/api/controller/link_handler.py
- gns3server/handlers/api/controller/node_handler.py
- gns3server/handlers/api/controller/project_handler.py
- gns3server/web/response.py
- gns3server/web/route.py
- requirements.txt
- scripts/random_query.py
- tests/controller/test_compute.py
- tests/handlers/api/base.py
- tests/handlers/api/controller/test_project.py
- tests/handlers/api/controller/test_symbol.py
> Aiohttp 2.0

- gns3server/controller/__init__.py
- tests/controller/test_controller.py
> Fix when config file doesn't have computes section

- gns3server/compute/qemu/qemu_vm.py
- gns3server/schemas/node.py
- gns3server/schemas/qemu.py
- tests/compute/qemu/test_qemu_vm.py
> Revert "Spice feature"

- gns3server/compute/qemu/qemu_vm.py
- gns3server/schemas/node.py
- gns3server/schemas/qemu.py
- tests/compute/qemu/test_qemu_vm.py
* QEMU VNC options tests
* QEMU - SPICE support at build options and schemas
* SPICE console_type for nodes
> Spice support

- gns3server/compute/dynamips/nodes/ethernet_switch.py
- gns3server/schemas/ethernet_switch.py
- gns3server/utils/asyncio/embed_shell.py
- tests/compute/dynamips/test_ethernet_switch.py
- tests/utils/asyncio/test_embed_shell.py
> Fake console for simple Ethernet switch

- gns3server/compute/iou/iou_vm.py
- gns3server/compute/iou/utils/application_id.py
- gns3server/controller/node.py
- gns3server/controller/project.py
- gns3server/schemas/iou.py
- tests/compute/iou/test_iou_vm.py
- tests/compute/iou/utils/test_application_id.py
- tests/controller/test_project.py
Possible solution for the IOU problem.
> Bugfix 557

- gns3server/controller/project.py
- gns3server/controller/topology.py
- gns3server/schemas/project.py
- gns3server/schemas/topology.py
- tests/controller/test_project.py
- tests/controller/test_topology.py
Reference: https://github.com/GNS3/gns3-gui/issues/2124
and
https://github.com/GNS3/gns3-gui/issues/712
> Graphics settings

- gns3server/controller/__init__.py
- gns3server/controller/compute.py
- gns3server/handlers/api/controller/compute_handler.py
- tests/controller/test_controller.py
- tests/handlers/api/controller/test_compute.py
Fix https://github.com/GNS3/gns3-gui/pull/2153
> Implement an api call for computing the IDLE PC

- gns3server/compute/base_node.py
- gns3server/compute/dynamips/__init__.py
- gns3server/compute/dynamips/nios/nio_udp.py
- gns3server/compute/dynamips/nodes/atm_switch.py
- gns3server/compute/dynamips/nodes/ethernet_hub.py
- gns3server/compute/dynamips/nodes/ethernet_switch.py
- gns3server/compute/dynamips/nodes/frame_relay_switch.py
- gns3server/compute/dynamips/nodes/router.py
- gns3server/compute/qemu/qemu_vm.py
- gns3server/compute/virtualbox/virtualbox_vm.py
- gns3server/compute/vpcs/vpcs_vm.py
> Use ubridge for dynamips routers

- gns3server/web/web_server.py
- requirements.txt
- tests/handlers/api/compute/test_project.py
- tests/handlers/api/compute/test_qemu.py
- tests/handlers/api/controller/test_node.py
- tests/handlers/api/controller/test_project.py
This upgrade should allow rolling release distribution to package the 2.1
> Upgrade to last aiohttp version

- gns3server/compute/base_node.py
- gns3server/controller/link.py
- tests/compute/test_base_node.py
- tests/controller/test_link.py
- tests/controller/test_udp_link.py
Fix https://github.com/GNS3/gns3-gui/issues/765
> BPF filter support

- gns3server/compute/base_node.py
- gns3server/compute/dynamips/nios/nio_udp.py
- gns3server/compute/dynamips/nodes/router.py
- gns3server/compute/vpcs/vpcs_vm.py
- gns3server/controller/link.py
- gns3server/handlers/api/compute/dynamips_vm_handler.py
- tests/compute/test_base_node.py
> Support packet filtering for dynamips

- gns3server/compute/base_node.py
- gns3server/compute/qemu/qemu_vm.py
- gns3server/compute/virtualbox/virtualbox_vm.py
- gns3server/compute/vpcs/vpcs_vm.py
- gns3server/run.py
- tests/compute/qemu/test_qemu_vm.py
- tests/compute/vpcs/test_vpcs_vm.py
- tests/conftest.py
- tests/controller/test_project_open.py
- tests/handlers/api/compute/test_qemu.py
- tests/handlers/api/compute/test_vpcs.py
Ref #1115
The PR is bigger than expected, because test was not running with use_ubridge enable
> Remove use_ubridge flag

- gns3server/compute/qemu/qemu_vm.py
- gns3server/controller/link.py
- gns3server/handlers/api/compute/qemu_handler.py
- tests/controller/test_link.py
- tests/handlers/api/compute/test_qemu.py
> Qemu support for packet filtering

- gns3server/compute/builtin/nodes/cloud.py
- gns3server/compute/nios/nio_udp.py
- gns3server/controller/link.py
- gns3server/handlers/api/compute/cloud_handler.py
- gns3server/handlers/api/compute/nat_handler.py
- tests/compute/builtin/nodes/test_cloud.py
- tests/compute/dynamips/test_ethernet_switch.py
- tests/compute/test_base_node.py
- tests/handlers/api/compute/test_cloud.py
- tests/handlers/api/compute/test_nat.py
> Filter implementation for cloud & Nat

- gns3server/compute/base_node.py
- gns3server/compute/iou/iou_vm.py
- gns3server/controller/link.py
- gns3server/handlers/api/compute/iou_handler.py
- tests/handlers/api/compute/test_iou.py
> Filters support for IOU

- gns3server/compute/virtualbox/virtualbox_vm.py
- gns3server/controller/link.py
- gns3server/controller/project.py
- gns3server/handlers/api/compute/qemu_handler.py
- gns3server/handlers/api/compute/virtualbox_handler.py
- tests/handlers/api/compute/test_virtualbox.py
> Packet filters support for VirtualBox

- gns3server/compute/vmware/vmware_vm.py
- gns3server/controller/link.py
- gns3server/controller/project.py
- gns3server/handlers/api/compute/vmware_handler.py
- tests/handlers/api/compute/test_vmware.py
> Filters support for VMware

- conf/gns3_server.conf
- gns3server/controller/__init__.py
- gns3server/controller/appliance_template.py
- scripts/remote-install.sh
- tests/conftest.py
- tests/controller/test_controller.py
Fix https://github.com/GNS3/gns3-gui/issues/2133
PR with two part: server and GUI
> Add an appliance templates directory

- gns3server/compute/base_manager.py
- gns3server/compute/base_node.py
- gns3server/compute/dynamips/__init__.py
- gns3server/compute/dynamips/nodes/router.py
- gns3server/compute/vpcs/vpcs_vm.py
- gns3server/controller/node.py
- gns3server/controller/project.py
- gns3server/handlers/api/compute/dynamips_vm_handler.py
- gns3server/handlers/api/compute/ethernet_switch_handler.py
- gns3server/handlers/api/compute/vpcs_handler.py
- gns3server/handlers/api/controller/node_handler.py
- gns3server/schemas/node.py
- tests/compute/dynamips/test_dynamips_manager.py
- tests/compute/test_manager.py
- tests/compute/vpcs/test_vpcs_vm.py
- tests/controller/test_project.py
- tests/handlers/api/compute/test_vpcs.py
- tests/handlers/api/controller/test_node.py
Support:
* VPCS
* Dynamips router
* Ethernet switch
Ref #1065
> API for duplication a Node

- gns3server/handlers/api/compute/qemu_handler.py
- tests/handlers/api/compute/test_qemu.py
Ref https://github.com/GNS3/gns3-gui/issues/1065
> Duplicate support for qemu

- gns3server/handlers/api/compute/iou_handler.py
- tests/handlers/api/compute/test_iou.py
Ref https://github.com/GNS3/gns3-gui/issues/1065
> Duplicate IOU

- gns3server/handlers/api/compute/docker_handler.py
- tests/handlers/api/compute/test_docker.py
Ref https://github.com/GNS3/gns3-gui/issues/1065
> Support duplicate for Docker

- gns3server/handlers/api/compute/atm_switch_handler.py
- gns3server/handlers/api/compute/ethernet_hub_handler.py
- gns3server/handlers/api/compute/frame_relay_switch_handler.py
Fix https://github.com/GNS3/gns3-gui/issues/1065
> Duplicate API for ATM, Ethernet Hub and Frame Relay Switch

- gns3server/handlers/api/controller/project_handler.py
- tests/controller/test_export_project.py
- tests/handlers/api/controller/test_project.py
Also add test to avoid regressions on this.
Fix https://github.com/GNS3/gns3-gui/issues/2165
> This fix the images always included in portable project

- gns3server/controller/appliance.py
- tests/controller/test_appliance.py
@grossmj I'm not sure if in this behavior should return None or not defined category, please check.
> Fixes not known category in Appliances (Fixes #1156)

- gns3server/handlers/api/compute/cloud_handler.py
@noplay do you have better idea what can be the reason?
> Added checking if NIO exists (Fixes #1160)

- gns3server/utils/asyncio/embed_shell.py
Just testing if it helps (Ref. #1172)
> Windows console bugfix tests

- gns3server/compute/base_node.py
- gns3server/compute/builtin/nodes/cloud.py
- gns3server/compute/docker/docker_vm.py
- gns3server/compute/iou/iou_vm.py
- gns3server/compute/project.py
- gns3server/compute/qemu/qemu_vm.py
- gns3server/compute/virtualbox/virtualbox_vm.py
- gns3server/compute/vmware/vmware_vm.py
- gns3server/compute/vpcs/vpcs_vm.py
- tests/compute/test_project.py
> Don't create directory structure during json dump. Fixes #2270

- gns3server/handlers/api/controller/node_handler.py
- tests/handlers/api/controller/test_node.py
Ref. https://github.com/GNS3/gns3-gui/issues/2276
Please merge after rc2. I need to test it after win build.
> Fixes path normalization during file upload on nodes (Fixes: #2276)

- gns3server/controller/compute.py
- gns3server/web/web_server.py
- requirements.txt
Support for aiohttp 2.3.1. Please don't merge it for now.
> aiohttp 2.3.1 support.

- gns3server/handlers/api/controller/drawing_handler.py
- gns3server/handlers/api/controller/link_handler.py
- tests/handlers/api/controller/test_drawing.py
- tests/handlers/api/controller/test_link.py
Fixes #1249
Initially I also wanted to include the changed `docs/api` files in this PR. But during the preparation I noticed, that lots of the current API documentation is outdated. Updating only a small part of the API documentation makes no sense, all the documentation should be updated. I'll create an issue for that.
> GNS3-API: implement GET for specific drawing and link

- gns3server/compute/docker/docker_vm.py
When a docker container was updated, the NIO UDP ports were being released
from port_manager, but they were still stored in self._ethernet_adapters.
When the container was restarted, the same NIO ports would be used. However,
if a new connection was then added, it could assign a port that was already
in use. The end result was that traffic would be bridged across the wrong
interface connection.
> Don't release NIO UDP ports when updating docker container.

- gns3server/compute/docker/docker_vm.py
- gns3server/utils/asyncio/telnet_server.py
This solves the issue reported in #1471 however the case when multiple Telnet consoles with different sizes are connected to the same Docker VM is not handled well. Each time a Telnet console is resized, this sends a resize event updating the same Docker VM TTY which may not work well for other consoles.
> Telnet console resize support for Docker VM. Fixes #1471

- gns3server/appliances/juniper-vmx-vcp.gns3a
- gns3server/appliances/juniper-vmx-vfp.gns3a
I have added some more recent releases of vMX
> Add vMX 17.4 and 18.4

- gns3server/compute/docker/docker_vm.py
- tests/compute/docker/test_docker_vm.py
Possible fix for https://github.com/GNS3/gns3-server/issues/1595
* Removes "Duplicate persistent volume" error message,
* Handles "/etc/network" mount consistently, and
* Selects most generic mount.
> Fix for issue #1595

- gns3server/compute/qemu/qemu_vm.py
- gns3server/handlers/api/compute/qemu_handler.py
Ref https://github.com/GNS3/gns3-gui/issues/2809
> Refresh mounted media after ISO switch

- .gitignore
- gns3server/config.py
> Added workaround for #1690

- conf/gns3_server.conf
Added symbols_path so everybody knows that's a config option.
> Add symbols_path

- gns3server/compute/base_node.py
- gns3server/handlers/api/compute/docker_handler.py
- gns3server/handlers/api/compute/dynamips_vm_handler.py
- gns3server/handlers/api/compute/iou_handler.py
- gns3server/handlers/api/compute/qemu_handler.py
- gns3server/handlers/api/compute/virtualbox_handler.py
- gns3server/handlers/api/compute/vmware_handler.py
- gns3server/handlers/api/compute/vpcs_handler.py
- gns3server/handlers/api/controller/node_handler.py
- gns3server/web/route.py
Support for websocket console. Some improvements could be done regarding the websocket forwarding process in the controller.
Ref: https://github.com/GNS3/gns3-gui/issues/2883
> Support for WebSocket consoles

- gns3server/handlers/api/controller/snapshot_handler.py
> Sort snapshots by (created_at, name)

- gns3server/compute/docker/docker_vm.py
There's currently no clipboard support for servers running on TigerVnc. TigerVnc clipboard support is provided by vncconfig that needs to be spawned for every display socket. The code changes above provides that functionality
> Add clipboard support for TigerVnc

- gns3server/compute/qemu/qemu_vm.py
- gns3server/schemas/qemu.py
- gns3server/schemas/qemu_template.py
This would fix this issue: https://github.com/GNS3/gns3-server/issues/1767
> Support to activate/deactive network connection state replication in Qemu

- gns3server/compute/docker/docker_vm.py
- gns3server/handlers/api/compute/docker_handler.py
- gns3server/schemas/docker.py
- gns3server/schemas/docker_template.py
- tests/compute/docker/test_docker_vm.py
Options to limit CPU and memory usage for Docker containers. Fixes https://github.com/GNS3/gns3-server/issues/486 and https://github.com/GNS3/gns3-gui/issues/2980
> Resource constraints for Docker VMs.

- README.rst
> fix(readme): update python version from 3.5.3 to 3.6

- gns3server/handlers/api/controller/symbol_handler.py
- gns3server/utils/picture.py
We need to create endpoint to get server dimensions for https://github.com/GNS3/gns3-web-ui/issues/1047
> Create endpoint in symbols handler to get symbol dimensions #1884

- gns3server/compute/base_manager.py
- gns3server/handlers/api/compute/dynamips_vm_handler.py
- gns3server/handlers/api/compute/iou_handler.py
- gns3server/handlers/api/compute/project_handler.py
- gns3server/handlers/api/compute/qemu_handler.py
- gns3server/handlers/api/controller/node_handler.py
- gns3server/handlers/api/controller/project_handler.py
- gns3server/handlers/index_handler.py
- gns3server/utils/path.py
- tests/handlers/api/compute/test_project.py
- tests/handlers/api/compute/test_qemu.py
- tests/handlers/api/controller/test_node.py
- tests/handlers/api/controller/test_project.py
Fix security issue reported in #1894
> Prevent directory traversal

- gns3server/controller/import_project.py
- gns3server/controller/snapshot.py
Fixes #1904
(Fix made and tested on 2.2 branch; let me know if you want this rebasing to master)
> Preserve auto_start/auto_open/auto_close when restoring snapshot

- conf/gns3_server.conf
- gns3server/handlers/api/compute/server_handler.py
- gns3server/schemas/server_statistics.py
> Revert "List disk usage for all mount points"

- gns3server/compute/qemu/qemu_vm.py
- tests/compute/qemu/test_qemu_vm.py
Handle the deprecated use of backing file without explicit backing format issue.
> Qemu 6.1 support

- gns3server/api/routes/controller/dependencies/authentication.py
- gns3server/api/routes/controller/dependencies/database.py
- gns3server/api/routes/controller/notifications.py
- gns3server/api/routes/controller/projects.py
- gns3server/db/models/permissions.py
- tests/api/routes/controller/test_permissions.py
- tests/api/routes/controller/test_roles.py
* Pass a JWT token as a query string
* Verify the token is valid
* Find the user from the token
* Check if the user is authorized to use the endpoint
> Secure websocket endpoints

- init/gns3.service.systemd
> update /var/run -> /run to meet FHS spec & Systemd best practices

- gns3server/api/routes/compute/compute.py
- gns3server/api/routes/controller/images.py
- gns3server/api/routes/controller/projects.py
- gns3server/compute/project.py
- gns3server/compute/qemu/__init__.py
- gns3server/controller/project.py
- gns3server/server.py
- gns3server/utils/path.py
- tests/api/routes/compute/test_compute.py
- tests/api/routes/compute/test_projects.py
- tests/api/routes/compute/test_qemu_nodes.py
- tests/api/routes/controller/test_projects.py
- tests/compute/test_project.py
- tests/conftest.py
- tests/controller/test_import_project.py
- tests/controller/test_project.py
- tests/controller/test_project_open.py
- tests/utils/test_path.py
"Local" command line parameter is only for stopping a server that has been started by the desktop GUI
> "Local" command line parameter only for one purpose

- gns3server/api/routes/controller/projects.py
- gns3server/api/server.py
- gns3server/controller/export_project.py
- gns3server/controller/import_project.py
- gns3server/schemas/__init__.py
- gns3server/schemas/controller/projects.py
- gns3server/utils/asyncio/aiozipstream.py
- gns3server/utils/zipfile_zstd/__init__.py
- gns3server/utils/zipfile_zstd/_patcher.py
- gns3server/utils/zipfile_zstd/_zipfile.py
- requirements.txt
- tests/api/routes/controller/test_projects.py
Compression level has also been added
> zstandard compression support for project export

- gns3server/api/routes/controller/projects.py
- gns3server/controller/project.py
- tests/api/routes/controller/test_projects.py
Lock/unlock all nodes and drawings in a project
> Global project lock and unlock

- gns3server/compute/base_node.py
My computer has 3 Ethernet adapter as below:
1. Ethernet (Intel Gigabit Network)
2. VMware Network Adapter VMnet1 (VMware Virtual Ethernet Adapter for VMnet1)
3. VMware Network Adapter VMnet8 (VMware Virtual Ethernet Adapter for VMnet8)
When I'm binding the interface to "Ethernet", the connection always binding to VMnet8.
I dive into the source code, and found the interface search algorithm uses "in" operator and not early return first result.
So It's runs to `"Ethernet" in interface["netcard"]` and match the last network adapter. (Because VMware Virtual **Ethernet** Adapter for VMnet8)
This PR fixes the issue, and using "exact match" in  interface["name"], then using in operator to find in interface["netcard"] if first case not found anything.
> fix: binding to wrong interface in windows

- conf/gns3_server.conf
- gns3server/core/tasks.py
- gns3server/db/tasks.py
- gns3server/schemas/config.py
- gns3server/utils/images.py
* Option to disable image discovery
* Do not scan the parent image directory
> Improve image discovery process

- scripts/remote-install.sh
- Added `WELCOME_SETUP=0` to resolve:
```
gns3-remote-install.sh: line 304: [: ==: unary operator expected
gns3-remote-install.sh: line 457: [: ==: unary operator expected
```
> remote-install.sh: added variable declaration

- gns3server/compute/qemu/qemu_vm.py
- tests/compute/qemu/test_qemu_vm.py
Hi
I believe that is easy to implement, so i saved you time :-)
I hope I kept the spirit of your code :-)
> qemu : with "virtio-net-pci", fix the speed and duplex

- scripts/remote-install.sh
- scripts/welcome.py
Fixed the upgrade option under welcome.py adding 3 options. GNS3 only, all packages, and a full system update.
Also added user permissions to sudoers.d/gns3 so the update could be executed without requesting the user password.
> Fixed updating system and GNS3 via welcome.py.

- scripts/remote-install.sh
* Support for deb822 source format
* Support for custom repository
* Drop Ubuntu trusty support
> Update remote install script

- gns3server/api/routes/controller/links.py
- gns3server/schemas/__init__.py
- gns3server/schemas/controller/links.py
- tests/api/routes/controller/test_links.py
#2510
@grossmj please look at this, hope I did not break anything
> Get iface/udp tunnel from links with Cloud,Nat

- .github/workflows/docker-build.yml
This PR introduces a GitHub Actions workflow that automates Docker image building and publishing to both GitHub Container Registry and Docker Hub.
- Added `.github/workflows/docker-publish.yml` workflow file
- Configured automated Docker builds on code changes
- Set up dual registry publishing (GHCR + Docker Hub)
- Implemented case-sensitivity fix for repository naming
- **Push triggers**: `main`, `master`, `enhancement/**`, `dev`
- **PR triggers**: Same branches for build validation
- **GitHub Container Registry**: `ghcr.io/username/repository:latest`
- **Docker Hub**: `dockerhub-username/repository:latest`
- Automatic lowercase conversion for GHCR compatibility
- Handles mixed-case GitHub usernames properly
1. **Checkout**: Uses `actions/checkout@v4`
2. **Authentication**: Login to both …
> Add automated Docker build and publish workflow
