GNS3/gns3-server

gns3server/modules/qemu/qemu_vm.py
To use Qemu v0.11.0 following patches to Qemu are needed:
https://github.com/shmygov/qemu-0.11.0-patches-for-gns3
To use Qemu v0.14.1 following patches to Qemu are needed:
https://github.com/shmygov/qemu-0.14.1-patches-for-gns3
These include new patches not contained in http://www.gns3.net/qemu/:
0003-qemu-0.11.0-monitor-udp.patch
0003-qemu-0.14.1-monitor-udp.patch
More testing needed with new Qemu versions.
=> Dynamically configure network connections of running QEMU VMs

gns3server/handlers/api/iou_handler.py, gns3server/modules/iou/iou_vm.py, tests/handlers/api/test_iou.py
I have try to do the same with dynamips but this part is not tested and it's deeply in the code and I fear to introduce a side effect because I can't do it in the handler.
From what I understand of the code we overwrite it at each create. It's the client which protect us against this.
=> Do not erase the IOU config if you already have one

README.rst, requirements.txt, setup.py
Similar to GNS3/gns3-gui#321 in purpose - the two files are simply not in sync.
Is python-dateutil needed btw?
I erred on the side of including it, but I honestly have no idea... a search of "dateutil" doesn't show any occurrences... Should it be removed from both places instead of being added to both?
=> Readme + setup.py/requrements.txt sync

gns3server/handlers/api/qemu_handler.py, gns3server/modules/qemu/__init__.py, tests/modules/qemu/test_qemu_manager.py
This is a prerequisite for a Qemu-img wizard, which searches for the Qemu-img binary on the local server using this method, to then invoke it.
The alternative is to duplicate the path finding code into gns3-gui, but that's IMHO unnecessary and just not a good idea.
=> Dedicated Qemu-img method and API call

gns3server.bat
Currently, gns3server.bat runs the main.py relative to the CWD. However, if your CWD is not the repo root, the server fails to start.
This is very problematic, as the GUI starts and connects to whatever server is specified in its config, and if you specify the absolute path to gns3server.bat there, you start Python with the gns3-gui CWD, not the gns3-server CWD, which ultimately means the specified main.py is not found.
This PR fixes that by making the gns3server.bat run relative to itself, not relative to the CWD. The actual CWD that Python sees is still the original CWD (the gns3-gui CWD if you run gns3server.bat indirectly from the GUI), as before, but the server starts successfully regardless of CWD.
=> CWD independance

gns3server/modules/qemu/qemu_vm.py
it showed hda_disk_interface instead, which resulted in an odd visual glitch in the GUI - hdb's interface would copy over from hda when you hit the apply button, which since I accidently stumbled on this, I now realize is because the server is contacted again (since Christmas, I was trying to find it within the GUI... happy new year btw!).
=> Fixed showing of Qemu hdb_disk_interface

gns3server/handlers/api/qemu_handler.py, gns3server/modules/qemu/__init__.py, gns3server/schemas/qemu.py, tests/modules/qemu/test_qemu_manager.py
Adds an API point to check if the server supports KVM. Returned as part of an object of "capabilities", that currently includes just KVM.
It's defined in this way to minimize "feature creep" - if similar functionality is later required for other system related Qemu checks, they should just be added as part of this response's output.
=> Check KVM support

gns3server/modules/dynamips/__init__.py, gns3server/modules/dynamips/nodes/router.py
Two change:
1) Dump the config when you stop the node. 
2) Disallow empty startup config. If it's empty send ! it's
avoid dynamips crash
Fix https://github.com/GNS3/gns3-gui/issues/914
=> Improve dynamips startup_config dump

gns3server/modules/vmware/__init__.py
Currently, the default VM location for VMware is at ```%USERPROFILE%\Documents\Virtual Machines```. But the Documents folder can be placed anywhere, independent from the user profile location. I for one have my user profile on my system drive, and most of my data folders (including the documents one) on a different drive.
And besides, according to the docs for version 12, on Windows Server, the default VM location is at a folder named "My Virtual Machines" rather than just "Virtual Machines".
This PR changes the default location to use the "Documents" folder, as found by a pywin32 call, and also checks if the windows is a server or domain controller, and uses "My Virtual Machines" if it is, and "Virtual Machines" otherwise.
I haven't tested an actual Windows Server installation with this …
=> VMware default VM location

gns3server/handlers/api/iou_handler.py, gns3server/handlers/api/qemu_handler.py, gns3server/handlers/api/vpcs_handler.py, gns3server/modules/base_vm.py, gns3server/modules/iou/iou_vm.py, gns3server/modules/qemu/qemu_vm.py, gns3server/modules/vpcs/vpcs_vm.py, gns3server/schemas/iou.py, gns3server/schemas/qemu.py, gns3server/schemas/vpcs.py, tests/handlers/api/test_iou.py, tests/handlers/api/test_qemu.py, tests/handlers/api/test_vpcs.py, tests/modules/iou/test_iou_vm.py, tests/modules/qemu/test_qemu_vm.py, tests/modules/vpcs/test_vpcs_vm.py
Add a command_line attribute to the VM object with
the command line used to start the VM.
Now /start return the object in order to get
this new attribute. And the HTTP status code
is 200 instead of 204 because 204 disallow body.
Support:
* Qemu
* Dynamips
* IOU
Ref https://github.com/GNS3/gns3-gui/issues/513
=> Send command line used to start the VM to client

gns3server/modules/docker/docker_vm.py, gns3server/modules/docker/resources/init.sh
Made the following changes:
- use image_infos.get("Config",...) instead of "ContainerConfig"
- init script injected before normal Entrypoint, so it's guaranteed to be the first command running
- init script has chmod +x, started without /bin/sh, because init script needs pid 1
- init script starts next script/program with exec, because (if it's a "real" init) it needs pid 1
- command line in GNS3 replaces command in docker, it's not appended. That's consistent with the "docker run" behavior
- A shell /bin/sh is only added, when Entrypoint and Cmd is empty
=> updated docker command line processing

scripts/remote-install.sh
Setup GNS3 and a VPN on a naked ubuntu server 14.04. For people who want to install it on public hosting provider.
To test it as root:
```
cd /tmp
curl https://raw.githubusercontent.com/GNS3/gns3-server/remote_install/scripts/remote-install.sh > gns3-remote-install.sh
bash gns3-remote-install.sh --with-openvpn
```
At the end you got an url to an openvpn config file.
On mac you can use it with tunnel blick.
After that you can add a server 172.16.253.1 as a GNS3 remote server
=> Remote install on 14.04 ubuntu

gns3server/modules/docker/docker_vm.py, gns3server/modules/docker/resources/bin/udhcpc, gns3server/modules/docker/resources/bin/udhcpc6, gns3server/modules/docker/resources/init.sh
Some minor cleanup
- avoid warnings by adding /etc/network/pre-up.d and post-down.d
- shell wrappers for udhcpc and udhcpc6 no longer necessary, script path has been changed in busybox
=> Minor cleanup on docker-init

gns3server/handlers/api/project_handler.py, gns3server/modules/project.py, gns3server/modules/project_manager.py, requirements.txt, tests/handlers/api/test_project.py, tests/handlers/test_upload.py, tests/modules/test_project.py
This provide an API for exporting a project directory as ZIP and importing it via the API.
For the moment I called this archive a gns3z (Zipped GNS3) but we probably will use a better name.
The export will ignore:
* snapshots
* logs files
Latter we will need to improve qemu to support file relocation.
The export code in the GUI is ready it's relatively small:
https://github.com/GNS3/gns3-gui/blob/46b0012e5c457d50ec890b89fed2f055d2f1cd87/gns3/utils/export_project_worker.py
The only missing part is the import before pushing a PR.
Ref: https://github.com/GNS3/gns3-gui/issues/476
=> Import export API

scripts/remote-install.sh
Some providers like packet doesn't  provide 32 bit repository. This block IOU installation
=> Allow to add 32 bit repositories when they are not available on the system

gns3server/utils/__init__.py, tests/test_utils.py
What  do you think @grossmj ?  I think It should support most semantic version comparaison (problem you should not use the output to display it to a user)
I could backport it to GUI if it's ok
Ref #515
=> Improve parse_version

gns3server/modules/docker/docker_vm.py, gns3server/modules/docker/resources/init.sh, tests/modules/docker/test_docker_vm.py
Proposal improve for waiting that all the eth interface are available in the container.
Fix #511
=> Wait for all interfaces available in container

gns3server/compute/dynamips/__init__.py, gns3server/compute/dynamips/nodes/router.py, gns3server/compute/iou/iou_vm.py, gns3server/utils/file_watcher.py, tests/utils/test_file_watcher.py
This monitor for change the file from dynamips by computing a
hash of the watched file.
The way dynamips work prevent the update of the modification time.
We can improve that by using native system for watching file but:
* it's require dependencies specific for each OS
* dependencies use C extensions
* this is only a backup if your router is cleanly shutdown we export
stuff
Ref https://github.com/GNS3/gns3-gui/issues/1243
=> Watch for dynamips rom & nvram change

gns3server/run.py
This is done only if you lock by pid to avoid killing process
of another server.
Fix #581
=> Kill ghosts process at startup (Dynamips, VPCS, Ubridge)

requirements.txt
Rolling release distribution (like alpine linux), has the new aiohttp version., which is 0.22.1. This patch allow GNS3 to be installed with newer aiohttp, rahter than sticking to a specific version.
I've already applied it in porting GNS3 to Alpine : http://git.alpinelinux.org/cgit/aports/commit/?id=b71b64c26a38d5c9ec6e2692e4179bcd798c8ace
I had no issue so far, even if GNS3 is still in testing and needs thorugh check.
Thanks for considering!
Francesco Colista
=> requirements.txt : added support for newer aiohttp version

conf/gns3_server.conf, init/gns3.service.systemd
Rewrote the systemd unit file to fix an issue where the system was not able to create a PID file inside /var/run.
I fixed this by having systemd create a new directory called /var/run/gns3. Then I had systemd change ownership of the directory to gns3:gns3 so the gns3server executable could read and write the PID file. I have tested these changes against Ubuntu 16.04.1 LTS.
=> Updated systemd unit file and added sample configuration file

gns3server/compute/qemu/qemu_vm.py
Qemu is the only platform where we limit the binding of UDP
tunnel to a specific host. It's probably much secure and cleaner
but we have scenario where we need one port bind to an IP and
another bind to a different IP (Link between qemu and and a VM on the
GNS3 VM)
This allow the use of 134fed8fc5d5f130275a7a1f19613427548ceb57
=> Bind qemu UDP tunnels on all hosts

gns3server/modules/port_manager.py
Because some emulators will listen on 0.0.0.0 and not on the host.
Fix #721
=> When checking for a free port check if the host and 0.0.0.0 are available

requirements.txt, setup.py
typing is now part of Python starting from 3.5, this PR exclude this requirement on such version.
=> typing is already included in Python >= 3.5

gns3server/compute/builtin/nodes/nat.py, tests/compute/builtin/nodes/test_nat.py, tests/handlers/api/compute/test_capabilities.py
On Windows and Mac OS this allow the NAT node to use the
VMware nat (it's always vmnet8). On Linux we still use the
libvirt NAT
=> NAT node can use the VMware NAT

gns3server/web/web_server.py
The server start to compute qemu image list in background
because first time discovery could be slow due to the compute
time of md5sum.
Fix #996
=> When connecting to a compute node ask for qemu images list

gns3server/controller/__init__.py, gns3server/controller/appliance.py, gns3server/controller/appliance_template.py, gns3server/controller/project.py, tests/controller/test_controller.py, tests/controller/test_project.py
The default VPCS template didn't provide the base
startup config setting. This prevent the replacement
of the hostname in the configuration file.
Fix https://github.com/GNS3/gns3-gui/issues/2123
=> Fix the initial startup for VPCS is not used

gns3server/controller/project.py
This fix random test failure when testing snapshots. It
seem under high load sometimes the previous snapshot folder
was not visible on disk. Perhaps a test isolation issue but
I don't see how.
But in any case it's better to test if the name is not already
use.
Fix #1118
=> Test if a snapshot name already exists

gns3server/controller/project.py
@grossmj I have doubts about this solution. I cannot judge if link_id is not set by user interaction in file (the most likely) or this bug has deeper source.
=> Fixes loading project when link_id is not set (#1159)

gns3server/compute/qemu/qemu_vm.py
gns3 server log doesn't show the base MAC address when creating a new qemu node (i.e when the mac address is auto-generated).
=> QEMU: fix logging of base mac address when creating a new node

gns3server/compute/dynamips/nodes/ethernet_switch.py, tests/compute/dynamips/test_ethernet_switch.py
From https://gns3.com/qa/ethernet-switch-incorrectly-has-
=> Rename ethernet switch shell command arp to mac

gns3server/compute/base_manager.py, gns3server/compute/qemu/qemu_vm.py, gns3server/utils/asyncio/__init__.py, gns3server/utils/images.py, tests/compute/qemu/test_qemu_vm.py, tests/utils/test_images.py
This should basically don't block GUI during computations. Further work requires change the way how we're taking care of images. In the long term we will look on that while working on computes changes (https://github.com/GNS3/gns3-server/issues/1186).
=>  Calculate MD5 on thread and before json response, Ref. gui#2239 

gns3server/handlers/api/compute/project_handler.py, gns3server/notification_queue.py, gns3server/utils/ping_stats.py
Ensures a minimum interval between two psutil.cpu_percent() calls. If CPU and memory are requested faster than this interval, the latest result is returned.
=> Implement a minimum interval between psutil calls. Fixes #2262

requirements.txt
Hi,
The typing package is already included in Python 3.5 and later and it can apparently cause failures for Python 3.7.
=> Require typing only for Python < 3.5

gns3server/compute/docker/resources/init.sh
Added `/sbin` to init script PATH variable so that its possible to use more sophisticated DHCP clients (compared to the udhcpc that is provided by busybox) by installing them into the docker image in the normal way.
This was done so that it was possible to set the client-id for DHCP by using dhclient installed into the docker image. The precedence is defined as follows:
> Clients are tried in the following order: dhcpcd, dhclient, pump and udhcpc.
The `interfaces` file configured within GNS3 for the docker image could then contain the following:
```
auto eth0
iface eth0 inet dhcp
pre-up echo "send dhcp-client-identifier 0:67:6e:73:33;"  > /etc/dhcp/dhclient.conf
```
That will set the client id to `gns3`.
=> Support for using other dhcp clients in docker init.sh

gns3server/compute/base_manager.py, gns3server/compute/dynamips/nodes/router.py, gns3server/compute/iou/iou_vm.py, gns3server/compute/qemu/qemu_vm.py, tests/handlers/api/compute/test_qemu.py
This is useful for Cisco VMs that will load a boot configuration if it appears on an ISO filesystem attached as a virtual CD-ROM, and boot configurations are logically part of the project, not global.
=> Allow virtual machines to use files in project directory as disk images

gns3server/compute/docker/docker_vm.py
x11vnc fails to start because of a typo:
vnc.log:
29/11/2018 00:24:06 *** unrecognized option(s) ***
29/11/2018 00:24:06 	[1]  -nopw-shared
=> Docker: fix x11vnc not starting

gns3server/controller/node.py, gns3server/handlers/api/controller/symbol_handler.py, gns3server/utils/picture.py
* Default for missing height/width is "100%" as defined in the SVG specification
* Better error message, if viewBox attribute is missing
* Removal of "%" in percent more fault tolerant by using rstrip("%")
=> Tune how to get the size of SVG images.

gns3server/compute/docker/docker_vm.py, gns3server/compute/docker/resources/init.sh, tests/compute/docker/test_docker_vm.py
(updated pull request https://github.com/GNS3/gns3-server/pull/1572 with an additional commit to fix failing tests)
Some docker images explicitly set the [runtime user](https://docs.docker.com/engine/reference/builder/#user) such as [graylog](https://hub.docker.com/r/graylog/graylog/). This means that the `init.sh` script used by gns3 inside docker will not work as it need root permissions.
This patch starts the container with root user, then uses `su` to drop to the desired user (or root if no user was configured) after `init.sh` has finished.
The `init.sh` has a little additional complexity to handle nested arguments, such as the convoluted example:
```
"Cmd": [
"/bin/sh",
"-c",
"cd /etc ; pwd ; exec /bin/sh -c \"cd /etc/network ; pwd ; exec /bin/sh\""
],
```
Please feel free to update …
=> Support for docker images that set the USER directive (+test coverage)

gns3server/compute/docker/docker_vm.py, gns3server/handlers/api/compute/docker_handler.py, gns3server/schemas/docker.py, tests/compute/docker/test_docker_vm.py
This is a small additional feature that I have been using for a short while to allow the user to specify additional persistent volumes to be mounted for a docker container. This mitigates the need to roll a `Dockerfile` that simply adds a `VOLUME` directive to enable a persistent directory to make the image feasible to use within GNS3.
One example of this is the (elastiksearch)[https://www.elastic.co/guide/en/elasticsearch/reference/current/docker.html] docker image that is often used by logging servers and is desirable to configure within GNS3 to evaluate.
The patch add the `extra_volumes` attribute to the docker appliance, which, when the container is created is merged in with the `volumes` already specified in the image.
=> Custom persistent docker volumes

gns3server/compute/qemu/qemu_vm.py, tests/compute/qemu/test_qemu_vm.py
A fixed id doesn't hurt and now we can select Disk Interface=none in
GNS3 and e.g. attach the volume as a USB thumb drive with -device
usb-storage,drive=drive0,...
It's also possible to override some options this way, such as the serial number of the ide drive.
=> Add id value to all qemu drives

gns3server/compute/qemu/qemu_vm.py
pci.X is not always defined, let qemu handle this.
I think PCI buses only exist if PCI network adapters are defined, this
is not the case with virtio.
=> Don't specify the PCI bus for AHCI device

gns3server/handlers/api/compute/server_handler.py, gns3server/handlers/api/controller/server_handler.py, gns3server/schemas/server_statistics.py, tests/handlers/api/compute/test_server.py, tests/handlers/api/controller/test_server.py
There are 2 endpoints.
On compute level (private API), statistics about CPU, memory, swap and disk are returned
GET `http://localhost:3080/v2/compute/statistics`
```
{
"cpu_usage_percent": 20,
"disk_usage_percent": 95,
"load_average_percent": [
30,
23,
21
],
"memory_free": 6105800704,
"memory_total": 16453206016,
"memory_usage_percent": 62,
"memory_used": 10347405312,
"swap_free": 12032184320,
"swap_total": 17179865088,
"swap_usage_percent": 30,
"swap_used": 5147680768
}
```
On controller level (public API), an array of computes is returned. Each entry has the compute ID and compute name along with the statistics specific to that compute.
GET `http://localhost:3080/v2/statistics`
```
[
{
"compute_id": "local",
"compute_name": "Coruscant",
"statistics": {
"cpu_usage_percent": 23, …
```
=> Server statistics implementation. Ref #1682

gns3server/compute/qemu/qemu_vm.py, gns3server/schemas/qemu_template.py
* Add "e1000-82544gc", "e1000-82545em", "e1000e" and "rocker" NIC models.
* Prevent running Qemu >= 2.9.0 with legacy mode.
* Fix scsi disk interface.
* Add nvme disk interface.
=> Recent Qemu versions support. Ref #1699

gns3server/controller/project.py, gns3server/handlers/api/controller/project_handler.py, gns3server/schemas/project.py
Added a option to reset or not all MAC addresses when exporting or duplicating a project. This fixes #1762
=> Option to reset MAC addresses when exporting or duplicating a project

gns3server/web/web_server.py
=> Use asyncio.all_tasks instead of deprecated method for Python 3.9 compatibility

gns3server/compute/qemu/qemu_vm.py
Clone the disk image in response to a resize request instead of waiting until the node starts.
=> Allow cloned QEMU disk images to be resized before the node starts

requirements.txt
`py-cpuinfo` was released a while back. According to the [Changelog](https://github.com/workhorsy/py-cpuinfo/blob/master/ChangeLog) it looks like a bugfix release.
The requirement are pinned and this causes build failures for distribution packages if the don't match the latest available release.
=> Set py-cpuinfo to 8.0.0

gns3server/compute/builtin/nodes/cloud.py, gns3server/compute/vmware/__init__.py, gns3server/compute/vmware/vmware_vm.py
VMware Fusion creates "bridge" interfaces (bridge100, bridge101 etc.) instead of the usual vmnet ones on macOS BigSur. Also, these interfaces are only created once a VM starts. This PR implements a way to find those bridge interfaces to be used in uBridge.
Should fix #1912 and https://github.com/GNS3/gns3-gui/issues/3106
=> Fix VMware VM support on macOS BigSur

setup.py
Hi,
I'm trying to get tests working for the gentoo ebuild, but have a minor issue with the installation.
For some reason the package tries to install the tests directory which it shouldn't do and which is why it got removed previously.
Now I was looking into it and it seems that, as soon as the tests directory has a `__init__.py` file, it wouldn't be excluded anymore by `find_packages` (even though it's clearly excluded there). This is also the reason why for example `gns3-gui` doesn't has this problem.
The proposed change fixes this issue.
=> setup.py: prevent installing tests directory

gns3server/compute/base_node.py
telnet_writer.write is not an async method - drain() is.
Remove async keyword so the call is the same as for the text websocket.
Using great [websocat](https://github.com/vi/websocat) socat, I try to access to console of apliances running inside GNS3.
```
$ websocat_amd64-linux -b \
tcp-listen:127.0.0.1:5000 \
ws://127.0.0.1:3080/v2/projects/0ac64a65-7f44-491e-b1b1-426c8a23129f/nodes/0af7b275-ed6d-4dc3-a36d-8b86a9686bfb/console/ws
```
This exposes telnet server of the remote console on  localhost port 5000.
I don't know (yet) why it doesn't work in textual mode, trying binary mode (above command, -b argument) revealed a bug that this pull request fixes. 
With this fix, it is now possible to connect to remote console using telnet command from the CLI.
=> Fix binary websocket access to the console

scripts/remote-install.sh
PR add improvements to script `remote-install.sh`:
- Add option `--without-kvm` that disables KVM support. Useful on systems that do not support nested virtualization (some cloud providers and hypervisors)
- Update GNS3 config to use newer parameters (`enable_hardware_acceleration` and `require_hardware_acceleration`)
- Fix hostname inconsistencies during script execution
- Other minor refactors
=> Update `remote-install.sh` with flag for KMS support and fix hostname inconsistencies

gns3server/compute/qemu/qemu_vm.py, gns3server/compute/qemu/utils/qcow2.py
This is a minimal changeset to address #1921.
This patch parses the json output from `qemu_img info`, both as a way of validating the image without calling `rebase`, and to obtain the base image virtual-size and encryption flag.
It uses the existing `_qemu_img_exec`, which mixes stdout and stderr together and writes them to `_qemu_img_stdout_file`, and is then read back by `read_qemu_img_stdout()`.  It works because the stderr output happens to be empty when there's valid info output on stdout.
Arguably it would be cleaner to separate stdout and stderr, either to two separate files, or a stderr file and RAM, or just read them both into RAM: e.g.
```
process = await asyncio.create_subprocess_exec(*command, stdout=asyncio.subprocess.PIPE,
stderr=asyncio.subprocess.PIPE, …
```
=> Support cloning of encrypted qcow2 base image files

conf/gns3_server.conf, gns3server/handlers/api/compute/server_handler.py, gns3server/schemas/server_statistics.py
Mount points can be restricted using a new setting `allowed_mountpoints` in gns3_server.conf
=> List disk usage for all mount points

gns3server/compute/qemu/qemu_vm.py, gns3server/compute/qemu/utils/qcow2.py
This allows importing portable projects with images and/or snapshots,
regression introduced by #1927.
Fixes #1955
=> Reinstate qemu-img rebase

gns3server/api/routes/controller/users.py
While trying this example with GNS3 branch 3.0 on Ubuntu 18.04.5 LTS, the REST API call 
```$ curl http://172.17.46.114:3080/v3/users/authenticate -d '{"username": "admin", "password": "admin"}' ``` 
fails with ```{"detail":[{"loc":["body"],"msg":"value is not a valid dict","type":"type_error.dict"}]}```.
The additional parameter appended to curl fixes this ```{"access_token":"eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJhZG1pbiIsImV4cCI6MTYzMTI4NTc4NX0.kT1dAN4v1vHMTBJO2UaI2I7yAFhnSpBU9iqmdDuwtAQ","token_type":"bearer"} ```
Found while googling for the error above in 
FastAPI 0.65.2 POST request fails with "value is not a valid dict" when using the Requests library; 0.65.1 works (with a caveat) #3373   https://github.com/tiangolo/fastapi/issues/3373#issuecomment-886745123
=> REST API example needs additional parameter

gns3server/compute/qemu/qemu_vm.py
Update the error message thrown when attempting to create a 2nd node when the template has "use as linked base VM" disabled (unchecked).
=> Update qemu_vm.py linked node error

gns3server/compute/base_manager.py, gns3server/compute/qemu/qemu_vm.py, gns3server/controller/appliance_manager.py, gns3server/controller/compute.py, gns3server/core/tasks.py, gns3server/db/tasks.py, gns3server/utils/images.py, requirements.txt, tests/utils/test_images.py
Images can be added on the filesystem in the default images directory before or after the server has been started. They are then automatically recorded in the controller database if not already done previously.
.md5sum files should go away since we have the database to record the image checksums
=> New images detection and checksum handling

gns3server/api/routes/controller/dependencies/authentication.py, tests/api/routes/controller/test_users.py
This is an alternative when the token cannot be passed in the HTTP header.
=> Allow JWT token to be passed as a URL param

gns3server/api/routes/compute/atm_switch_nodes.py, gns3server/api/routes/compute/cloud_nodes.py, gns3server/api/routes/compute/docker_nodes.py, gns3server/api/routes/compute/dynamips_nodes.py, gns3server/api/routes/compute/ethernet_hub_nodes.py, gns3server/api/routes/compute/ethernet_switch_nodes.py, gns3server/api/routes/compute/frame_relay_switch_nodes.py, gns3server/api/routes/compute/images.py, gns3server/api/routes/compute/iou_nodes.py, gns3server/api/routes/compute/nat_nodes.py, gns3server/api/routes/compute/projects.py, gns3server/api/routes/compute/qemu_nodes.py, gns3server/api/routes/compute/virtualbox_nodes.py, gns3server/api/routes/compute/vmware_nodes.py, gns3server/api/routes/compute/vpcs_nodes.py, gns3server/api/routes/controller/appliances.py, gns3server/api/routes/controller/computes.py, gns3server/api/routes/controller/controller.py, gns3server/api/routes/controller/drawings.py, gns3server/api/routes/controller/groups.py, gns3server/api/routes/controller/images.py, gns3server/api/routes/controller/links.py, gns3server/api/routes/controller/nodes.py, gns3server/api/routes/controller/permissions.py, gns3server/api/routes/controller/projects.py, gns3server/api/routes/controller/roles.py, gns3server/api/routes/controller/snapshots.py, gns3server/api/routes/controller/symbols.py, gns3server/api/routes/controller/templates.py, gns3server/api/routes/controller/users.py
Thanks to aiohttp 0.79.0 we no longer have to explicitly return Response object when an endpoint does not return any content (HTTP status code 204)
=> Remove explicit Response for endpoints returning HTTP 204 status code

init/gns3.service.openrc
Hi,
This is a small change to the open script to make it POSIX compliant.
I've also removed a trailing whitespace from the script.
Regards
Michael
=> gns3.service.openrc: make openrc script posix compliant

scripts/remote-install.sh, scripts/welcome.py
1. Update the remote-install.sh script to support Ubuntu Server LTS 22.10
2. Add the option to setup the welcome.py from GNS3-VM dialog to remote-install.sh using the --with-welcome option
3. Update welcome.py to run in on  Ubuntu Server LTS 22.10 outside of GNS3-VM
welcome.py is essentially Identical to the one included with GNS3VM with these changes:
1. refactored to wrap all the functions inside a class
2. updated the method get_ip() to work on any enviroment. It pulls the first system IP that is not a vbridge or loopback
3. New method repair_remote_install() that is callable from remote-install.sh to update the IP in gns3_server.conf and restart the gns3 service ensure Dialog always displays the same IP we wrote to gns3_server.conf.
The final merge assumes that welcome.py has already …
=> Update remote-install.sh and add welcome.py

gns3server/compute/docker/docker_vm.py, tests/compute/docker/test_docker_vm.py
Mounts are used instead of volumes
=> Allow ':' in project name when using Docker containers

gns3server/handlers/api/controller/template_handler.py
According to the documentation the endpoint `/v2/projects/{project_id}/templates/{template_id}` accepts `name` for node in body ([accepted input](https://api.gns3.net/en/latest/api/v2/controller/template/projectsprojectidtemplatestemplateid.html#input)). In handler code this parameter is never parsed.
=> Parse name for request to node creation from template

gns3server/compute/docker/docker_vm.py, tests/compute/docker/test_docker_vm.py
Fix issues that a Docker container can remove the X11 socket of the host and that a Docker container has access to all X11 host sockets.
=> Prevent X11 socket file to be modified by Docker container

gns3server/api/routes/controller/__init__.py, gns3server/api/routes/controller/privileges.py, tests/api/routes/controller/test_privileges.py
Hello,
This PR is about Web UIv3 improvements.
We expose a new Endpoint /v3/access/privileges to get a list of all privileges.
privilege_id is required to update privileges associate to a role.
The endpoint have no privileges control.
Regard
Sylvain121
=> API: add endpoint to expose availables privileges to web UI

gns3server/db/repositories/rbac.py
On current version of PUT /v3/access/roles/{role_id}/privileges/{privilege_id}, database allow inserting multiple time same privilege for a role.
This generates an error when trying to DELETE the privilege.
This patch silent ignores request if privilege is already applied for the role.
=> rbac fix: cannot add multiple time same privilege to a role

.github/workflows/testing.yml, dev-requirements.txt, gns3server/server.py, pyproject.toml, requirements.txt
Python 3.7 is end-of-life and it is starting to be challending to support it because many of the latest dependency versions already don't.
https://endoflife.date/python
https://devguide.python.org/versions/
=> Drop Pyhton 3.7 support (end-of-life)

scripts/welcome.py
Fixed an issue where the shell option in dialog failed to drop you back to bash.
This commit will cause this version of the welcome.py dialog to differ from the one included with the GNS3 VM found [here](https://github.com/GNS3/gns3-vm/blob/master/scripts/welcome.py)
While very usable there are numerous bugs the with welcome.py dialog when installed via remote-install.sh.
If having this version of welcome.py differ from the [VM version](https://github.com/GNS3/gns3-vm/blob/master/scripts/welcome.py) is not a concern I can go through and easily clean up most of these issues.
=> [Fix] an issue where the shell option in dialog failed to drop you back to bash.

gns3server/utils/asyncio/telnet_server.py
Add wait_for for drain() call with a 5 second timeout. If we're stuck on drain then the buffer isn't getting emptied. 5 seconds after drain() blocks, exception will be thrown and client will be removed from connection table and will no longer be a problem. There will be a pause in console output while in this 5 second wait, after that the console will return to normal. 
When the exception is triggered the follow debug will be logged.
2024-02-03 03:07:15 DEBUG telnet_server.py:309 Timeout while sending data to client: ('REMOTE_IP', REMOTE_PORT), closing and removing from connection table. 
It just dawned on me that peerinfo() is a list so if you want that reformatted it would be easy enough to do. 
Fixes [Issue 2344](https://github.com/GNS3/gns3-server/issues/2344)
=> Address the telnet console death bug. 

gns3server/compute/docker/__init__.py, gns3server/compute/docker/docker_vm.py, gns3server/controller/__init__.py, setup.py, tests/compute/docker/test_docker.py, tests/compute/docker/test_docker_vm.py
This is backported from v3.0.
All files are installed at runtime, including busybox.
=> Install Docker resources in writable location

gns3server/compute/docker/resources/init.sh
* `busybox --install` does not exist anymore. Solution: manual install.
* `sleep` does not take float values (e.g. 0.5) anymore. Solution: use `usleep` instead
=> Fix issues with recent busybox versions

scripts/remote-install.sh
When rebuilding my server I found an issue when the --with-welcome option was used.
Ubuntu has locked down using pip in the global name-space so python3-dialog is now being installed via apt. This also removes the need for upgrading pip which could cause update issues.
=> Fixed issues with installing on Ubuntu 24.04 via remote-install.sh

scripts/remote-install.sh
Hi! Added four lines to `remote-install.sh` that check if the script is being run as root, as mentioned in the [docs](https://docs.gns3.com/docs/getting-started/installation/remote-server)
=> Check if remote-install.sh is being run as root

Dockerfile, README.md, compose.yaml
This pull request updates the Dockerfile base image from Ubuntu 18.04 to Ubuntu 24.04. Additionally, it adds a compose.yaml file to enable launching the application using the `docker compose` command.
* Updated the base image from ubuntu:18.04 to ubuntu:24.04.
* Updated the ENV syntax to the [recommended format ENV](https://docs.docker.com/reference/build-checks/legacy-key-value-format/) key="value". 
* Updated the CMD syntax to the [recommended JSONArgsRecommended](https://docs.docker.com/reference/build-checks/json-args-recommended/)
* Configured the file to allow easy startup with docker compose up.
I have updated the Dockerfile, but have not been able to fully test it.
=> Update Dockerfile base image to Ubuntu 24.04

gns3server/compute/qemu/qemu_vm.py
This small PR resolves deprecation warnings of regex library in Python3.13+:
```python
/home/runner/work/gns3-server/gns3-server/gns3server/compute/qemu/qemu_vm.py:228: DeprecationWarning: 'count' is passed as positional argument
```
=> Resolve deprecation warnings of regex library
